// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { getFirebaseAuth, isFirebaseAuthEnabled } from "@/integrations/firebase/config";

const stripBom = (s: string | undefined) => (s ?? "").replace(/^\uFEFF/, "").trim();
const SUPABASE_URL = stripBom(import.meta.env.VITE_SUPABASE_URL);
const SUPABASE_PUBLISHABLE_KEY = stripBom(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);

const supabaseOptions: Parameters<typeof createClient<Database>>[2] = {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
};

if (isFirebaseAuthEnabled()) {
  supabaseOptions.accessToken = async () => {
    const auth = getFirebaseAuth();
    const user = auth?.currentUser ?? null;
    const token = await user?.getIdToken(false) ?? null;
    return token;
  };
}

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  supabaseOptions
);